export const REGISTER_MEMBER = 'REGISTER_MEMBER';
export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM';
export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
export const GET_GEOLOCATION = 'GET_GEOLOCATION';
export const CHANGE_FILE_FIELD = 'CHANGE_FILE_FIELD';
export const SUCCESS_USER_AUTHENTICATION = 'SUCCESS_USER_AUTHENTICATION';
