export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
export const SUCCESS_USER_AUTHENTICATION = 'SUCCESS_USER_AUTHENTICATION';
export const CONFIRMED_NOT_AUTHENTICATED = 'CONFIRMED_NOT_AUTHENTICATED';
export const SUCCESS_REGISTER_MEMBER = 'SUCCESS_REGISTER_MEMBER';
export const USER_LOGOUT = 'USER_LOGOUT';

export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM';
export const SUCCESS_USER_DATA_UPDATE = 'SUCCESS_USER_DATA_UPDATE';

export const GET_GEOLOCATION = 'GET_GEOLOCATION';

export const LOADING_USERS = 'LOADING_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const INCREASE_CHOICE_COUNT = 'INCREASE_CHOICE_COUNT';
export const RESET_CHOICE_COUNT = 'RESET_CHOICE_COUNT';
export const INCREASE_PAGE_INDEX = 'INCREASE_PAGE_INDEX';
export const SELECTED_ALL_MEMBERS = 'SELECTED_ALL_MEMBERS';
export const ADD_NEW_USERS_LIST = 'ADD_NEW_USERS_LIST';
export const LEAVE_MEMBERS_LIST = 'LEAVE_MEMBERS_LIST';

export const LOAD_CHATS_LIST_SUCCESS = 'LOAD_CHATS_LIST_SUCCESS';
export const ENTER_CHAT_ROOM = 'ENTER_CHAT_ROOM';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const CHANGE_EDIT_FORM = 'CHANGE_EDIT_FORM';
export const NONE_CHATS = 'NONE_CHATS';
